import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import {ReactNode} from "react";
import Script from 'next/script';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout(props: RootLayoutProps) {
  const { children } = props

  return <html lang={'en'}>
  <head>
    {/*<Script*/}
    {/*    src={`https://cdn-cookieyes.com/client_data/aede9197ab354614db98ff51/script.js`}*/}
    {/*    strategy="beforeInteractive"*/}
    {/*/>*/}
    <Script
        id="Cookiebot"
        src="https://consent.cookiebot.com/uc.js"
        data-cbid="af730fb6-83b9-49b4-9c79-d36710d1c29b"
        data-blockingmode="auto"
        type="text/javascript" />
  </head>
  {children}
  </html>


}
