import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import {Header} from "@/src/shared/components/Header";
import {ReactNode} from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//     <head>
//       <link rel="icon" href="/favicon_32.png" sizes="32x32"/>
//       <link rel="icon" href="/favicon_64.png" sizes="64x64"/>
//       <link rel="apple-touch-icon" href="/favicon_128.png"/>
//       <link rel="icon" type="image/svg+xml" sizes="any" href="/favicon.svg" />
//       <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5, minimum-scale=1"/>
//     </head>
//       <body className={inter.className} suppressHydrationWarning={true}>{children}</body>
//     </html>
//   );
// }


type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout(props: RootLayoutProps) {
  const { children } = props

  return children;
}
